builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X main.build={{.Version}}
